version: '3'
services:
  redis:
    image: app-redis
    build:
      context: .
      dockerfile: Dockerfile-redis
    volumes:
      - $PWD/redis_data:/data

  flask:
    image: app-flask
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      # remove the following two for production deployment
      - $PWD/app:/home/flaskdemo/app
      - $PWD/webexintegration:/home/flaskdemo/webexintegration
    depends_on:
      - redis

  nginx:
    image: app-nginx
    build:
      context: .
      dockerfile: Dockerfile-nginx
    # remove volumes for production deployment
    volumes:
      - $PWD/nginx:/etc/nginx
      - $PWD/app/static/:/usr/share/nginx/html/static
    ports:
      - 5000:5000
    depends_on:
      - flask