version: '3'
services:
  redis:
    image: flask-realtime-redis
    build:
      context: .
      dockerfile: Dockerfile-redis
    volumes:
      - "./redis_data:/data"

  flask:
    image: flask-realtime-flask
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "./app:/home/flaskdemo/app"
      - "./webexintegration:/home/flaskdemo/webexintegration"
    depends_on:
      - redis

  nginx:
    image: flask-realtime-nginx
    build:
      context: .
      dockerfile: Dockerfile-nginx
    # remove volumes for production deployment
    volumes:
      - "./nginx:/etc/nginx"
      - "./app/static/:/usr/share/nginx/html/static"
    ports:
      - 5000:5000
    depends_on:
      - flask