version: '3'
services:
  redis:
    image: jeokrohn/app-redis
    volumes:
      - "./redis_data:/data"

  flask:
    image: jeokrohn/app-flask
    depends_on:
      - redis
    volumes:
      -"./webexintegration:/home/flaskdemo/webexintegration"

  nginx:
    image: jeokrohn/app-nginx
    ports:
      - 5000:5000
    depends_on:
      - flask