name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: build and push images
      run: |
        docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASS }}
        docker-compose -f docker-compose-dev.yml build
        docker tag flask-realtime-flask ${{ secrets.DOCKER_USER }}/flask-realtime-flask
        docker tag flask-realtime-nginx ${{ secrets.DOCKER_USER }}/flask-realtime-nginx
        docker tag flask-realtime-redis ${{ secrets.DOCKER_USER }}/flask-realtime-redis
        docker push ${{ secrets.DOCKER_USER }}/flask-realtime-flask
        docker push ${{ secrets.DOCKER_USER }}/flask-realtime-nginx
        docker push ${{ secrets.DOCKER_USER }}/flask-realtime-redis
        docker logout
